config/routes.rb
Rails.application.routes.draw do
  resources :to_dos

  root to: 'todos#index'

end

app/models/to_do.rb
class ToDo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  before_action :set_to_do, only: [:show, :edit, :update, :destroy]

  # GET /to_dos
  # GET /to_dos.json
  def index
    @to_dos = ToDo.all
  end

  # GET /to_dos/1
  # GET /to_dos/1.json
  def show
  end

  # GET /to_dos/new
  def new
    @to_do = ToDo.new
  end

  # GET /to_dos/1/edit
  def edit
  end

  # POST /to_dos
  # POST /to_dos.json
  def create
    @to_do = ToDo.new(to_do_params)

    respond_to do |format|
      if @to_do.save
        format.html { redirect_to @to_do, notice: 'To do was successfully created.' }
        format.json { render :show, status: :created, location: @to_do }
      else
        format.html { render :new }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_dos/1
  # PATCH/PUT /to_dos/1.json
  def update
    respond_to do |format|
      if @to_do.update(to_do_params)
        format.html { redirect_to @to_do, notice: 'To do was successfully updated.' }
        format.json { render :show, status: :ok, location: @to_do }
      else
        format.html { render :edit }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_dos/1
  # DELETE /to_dos/1.json
  def destroy
    @to_do.destroy
    respond_to do |format|
      format.html { redirect_to to_dos_url, notice: 'To do was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do
      @to_do = ToDo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def to_do_params
      params.require(:to_do).permit(:title, :notes, :due, :done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/to_dos/_form.html.erb
<%= form_for(@to_do) do |f| %>
  <% if @to_do.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@to_do.errors.count, "error") %> prohibited this to_do from being saved:</h2>

      <ul>
      <% @to_do.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.date_select :due %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/to_dos/edit.html.erb
<h1>Editing to_do</h1>

<%= render 'form' %>

<%= link_to 'Show', @to_do %> |
<%= link_to 'Back', to_dos_path %>

app/views/to_dos/index.html.erb
<h1>Listing to_dos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Notes</th>
      <th>Due</th>
      <th>Done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @to_dos.each do |to_do| %>
      <tr>
        <td><%= to_do.title %></td>
        <td><%= to_do.notes %></td>
        <td><%= to_do.due %></td>
        <td><%= to_do.done %></td>
        <td><%= link_to 'Show', to_do %></td>
        <td><%= link_to 'Edit', edit_to_do_path(to_do) %></td>
        <td><%= link_to 'Destroy', to_do, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New To do', new_to_do_path %>

app/views/to_dos/new.html.erb
<h1>New to_do</h1>

<%= render 'form' %>

<%= link_to 'Back', to_dos_path %>

app/views/to_dos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @to_do.title %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @to_do.notes %>
</p>

<p>
  <strong>Due:</strong>
  <%= @to_do.due %>
</p>

<p>
  <strong>Done:</strong>
  <%= @to_do.done %>
</p>

<%= link_to 'Edit', edit_to_do_path(@to_do) %> |
<%= link_to 'Back', to_dos_path %>